# Generated by Django 4.2.7 on 2024-01-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='displaycart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.additem')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reguser')),
            ],
        ),
    ]
