# Generated by Django 4.2.7 on 2024-01-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_quantity_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
