# Generated by Django 4.2.7 on 2024-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_additem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='stock',
            field=models.IntegerField(max_length=20),
        ),
    ]
