# Generated by Django 4.2.7 on 2024-01-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
