# Generated by Django 4.2.7 on 2024-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regshop',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
