# Generated by Django 4.2.7 on 2024-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_regshop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
