# Generated by Django 4.2.7 on 2024-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_additem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='category',
            field=models.CharField(default='vegerable', max_length=20),
        ),
    ]
