# Generated by Django 4.2.7 on 2024-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_additem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='regshop',
            name='profaile',
            field=models.FileField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
