# Generated by Django 4.2.7 on 2024-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_profaile_regshop_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='regshop',
            name='status',
            field=models.BooleanField(default='True'),
        ),
    ]
